### ISSUE TITLE
build import failed 

### ISSUE THREAD

**Issue by KKnapik** [kvaes/TasmanianTraders-IaC-Network#1]
Unfortunately I'm getting error when trying to import build definition - 
Extension Export/Import Build Definition is installed in my VSTS. 

Error message: " Either exported JSON is not valid or it is not compatible with current product. Please export again and try importing again "

**Comment by kvaes** [comment]
Could you try cleaning up the GUIDs from the JSON? It might be due that there is still a reference in there...

**Comment by KKnapik** [comment]
Compared your json settings file with one I've just exported. It seems that  since your last export the structure of json settings file has changed. 

The build Phase steps in your json are described in "build" section instead of "process" as it is in latest version : ( 

I'm afraid that re-export might only help here. 

Below examples. 


Former structure: 

"version": "0.3",
    "definition": {
        "build": [
            {
                "enabled": true,
                "continueOnError": false,
                "alwaysRun": false,
                "displayName": "Run Pester Tests",
                "timeoutInMinutes": 0,
                "task": {
                    "id": "",
                    "versionSpec": "1.*",
                    "definitionType": "task"
                },
                "inputs": {
                    "ConnectedServiceNameSelector": "ConnectedServiceNameARM",
                    "ConnectedServiceName": "",
                    "ConnectedServiceNameARM": "",
                    "ScriptType": "FilePath",
                    "ScriptPath": "invokePester.ps1",
                    "Inline": "# You can write your azure powershell scripts inline here. \n# You can also pass predefined and custom variables to this script using arguments",
                    "ScriptArguments": ""
                }
            },
 
Latest one: 

 "process": {
        "phases": [
            {
                "steps": [
                    {
                        "environment": {},
                        "enabled": true,
                        "continueOnError": false,
                        "alwaysRun": false,
                        "displayName": "Copy Publish Artifact: Files",
                        "timeoutInMinutes": 0,
                        "condition": "succeeded()",
                        "refName": "CopyPublishBuildArtifacts2",
                        "task": {

**Comment by kvaes** [comment]
I've uploaded a current export... Let me know if that works for you.

**Comment by KKnapik** [comment]
Works like a charm... 
Much appreciate that, Thank you ! 

![image](https://user-images.githubusercontent.com/30213322/38888250-5f7bbb4e-427b-11e8-85e4-bfea5b84500e.png)
